### ISSUE TITLE
PDF doesnt show photo / change title

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#105]
When I make a PDF of signal 650:
- The title in the document is SIA-650. This should be Signalen-650 or Melding 650
- The title of the fav icon is SIA melding 650. This should be Signalen melding 650 or Melding 650
- When I save the document the suggested title is SIA melding 650. This should be Signalen melding 650 or Melding 650
- Stadsdeel is specified as _none_. This should be _Binnenstad_ in this case
- The photo of the signalen is not shown in the PDF in the photosection

[SIA melding 650.pdf](https://github.com/Signalen/backend/files/5746416/SIA.melding.650.pdf)

**Comment by CBuiVNG** [comment]
see pull request: https://github.com/Amsterdam/signals/pull/679
