### ISSUE TITLE
Store `area` in a saved filter

### ISSUE THREAD

**Issue by boris-arkenaar** [Signalen/backend#111]
The `area` (district) is not being accepted when saving a filter.

A POST or PATCH call to `/signals/v1/private/me/filters/` should accept `area` in the `options`.

Example request payload:
```
{
  "name": "Filter name",
  "refresh": false,
  "options": {
    "area": ["123"]
  }
}
```

Current response payload:
```
{
  "options": [
    "FilterSet data to store contains unknown filters ['area']"
  ]
}
```

**Comment by CBuiVNG** [comment]
Looks like you need to use "area_code" instead of "area"
