### ISSUE TITLE
Exclude status Geannuleerd & Verzoek tot heropenen in public map endpoint

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#127]
Signals with status _Geannuleerd_ and _Verzoek tot heropenen_ are shown on de public map with open signals. We like to exclude both statuses from being shown on the map. This is on top of status _Afgehandeld_ & _Extern: afgehandeld_ which are already excluded from being shown on the map.

**Comment by CBuiVNG** [comment]
https://github.com/Amsterdam/signals/pull/741
