### ISSUE TITLE
Setup testing WFS service for Utrecht

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#142]
- [x] Create a Helm chart -> [Created](https://github.com/Signalen/helm-charts/releases/tag/mapserver-2.5.0)
- [x] Deploy on Utrecht namespace -> [Deployed](https://github.com/Signalen/infra/blob/master/directvps/apps/tenants/utrecht-mapserver.yaml)
- [x] Configure mapserver

**Comment by someren** [comment]
Vraag van gemeente 's-Hertogenbosch: Gaat het hier om een WFS die Signalen "serveert" (verstrekt zoals Signalen een API verstrekt) of een WFS die Signalen "op-soupeerd" (van een andere partij verstrekt krijgt en integreert binnen Signalen bijvoorbeeld op de kaart om een asset weer te geven)?

**Comment by bartjkdp** [comment]
@someren in detail beantwoord via Slack. Het gaat om een externe WFS service die gebruikt wordt binnen Signalen en gekoppeld wordt als additionele vraag.
