### ISSUE TITLE
Add file type validation by using header inspection, only accept images

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#147]
As a follow-up of https://github.com/Amsterdam/signals/pull/769 we would like to add file type validation by using header inspection.

Suggestion of @ericherman: 
- https://github.com/ahupp/python-magic

**Comment by tcoenen** [comment]
This corresponds to ticket SIG-3667 that is in the current Amsterdam development sprint - I will update this ticket with a reference to a PR once we have one.

**Comment by tcoenen** [comment]
Proposed implementation currently under review: https://github.com/Amsterdam/signals/pull/790
