### ISSUE TITLE
Create small script to calculate "servicebelofte" for all signals in the database

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#150]
Currently we only calculate "servicebelofte" for newly created Signals. This was a show-stopper for releasing a new version to 's-Hertogenbosch production.

**Comment by CBuiVNG** [comment]
`python api/app/manage.py calculate_deadlines
Using local database information
Find open Signals without deadlines ...
... re-assign category (triggering deadline calculation).
Number of signals without deadlines 290
Done`

**Comment by bartjkdp** [comment]
Nice 👍
