### ISSUE TITLE
Unable to connect to https://signalen.s-hertogenbosch.dev/manage on iPhone

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#29]
When logging on to the manage portal I get an error:
![image](https://user-images.githubusercontent.com/66015874/83730263-1dbd7380-a649-11ea-96b4-d7a53edb5200.png)

**Comment by bartjkdp** [comment]
This probably has to to with an outdated service worker. When we configure new settings, the service worker is not updated. Does cleaning the Safari cache work? (Settings > Safari > Clear History and website data)

**Comment by bartjkdp** [comment]
We will fix this in #49
