### ISSUE TITLE
Replace Elastic Search with pg full text search

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#3]
Original by @CBuiVNG 

Elastic is overkill for this project. Deployment will be easier (less dependencies, cost) if we can replace Elastic search with standard pg fulltext search.

**Comment by spreeker** [comment]
Please discuss this in depth with @david since there is quite some effort that went into this for some reasons and a elastic is pretty easy to run. imho.

**Comment by bartjkdp** [comment]
We will leave ElasticSearch in for now as the installation can be automated with Helm charts.
