### ISSUE TITLE
Adding a photo to a notification seems to be broken

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#37]
When a user is trying to upload a photo to his notification, he gets an error message saying _Uploaden van de foto is niet gelukt_. This functionality doesn't seem to be working correctly.

![image](https://user-images.githubusercontent.com/66015874/83970584-b6b4ee80-a8d6-11ea-99a4-0005213a642d.png)

**Comment by janjaap** [comment]
@bartjkdp The image endpoint is a bit quirky; you can upload multiple images for an incident, but the database only accepts one single image. When selecting two big (e.g. 2MB) images, uploading won't work. When selecting two images of different sizes, uploading will succeed.

**Comment by bartjkdp** [comment]
@janjaap thanks for letting me know  👍
