### ISSUE TITLE
Routing signals, assignment groups and assignees

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#53]
- As an administrator I would like to define routing rules so that I can route specific signals to an assignment group
- As a member of an assignment group I would like to see all signals in the group, see the assignees and claim a specific signal

**Note**

- Signals that are not routed to a specific assignment group can be filtered as well
- Maybe reuse departments for assignment groups?

## Current behavior

- User logs in to the back-office.
- invokes `/signals/v1/private/me/` to get permissions, departments,...
- invokes `/signals/v1/private/signals/?page=1&ordering=-created_at&page_size=50` to retrieve signals
- invokes `/signals/v1/private/me/filters/` to retrieve stored filters
- invokes `/signals/v1/private/categories/` to retrieve all categories

Currently there's a relation between category and department. A department is responsible for handling assigned signals.
In case of a split signal, multiple departments can be responsible for the sub-signals. There's one 'managing' department (`directing_department`) overseeing the original signal. 

When retrieving signals using the `/signals/v1/private/signals/?page=1&ordering=-created_at&page_size=50` call, the back-end [does filter signals based on user department](https://github.com/Amsterdam/signals/blob/master/api/app/signals/apps/signals/querysets.py).

### Back-end:
- Add models:
*RoutingRule* (relation between expression and department)
Fk to expression
Fk to department
description (text)
unique_together(fk_expr, fk_dept)
- *DepartmentSignal* (**optional** relation between signal and assigned department via rules)
FK to department
FK to Signal
unique_together(fk_dept, fk_signal)

- Add Routing endpoint to add, delete, modify rule-expression relation from the front-end
- Extend signal handler ('django signals') with rule evaluation -> assign to department logic. **Or** create a background task that handles unassigned signals every `n` minutes. 
-- If a rule matches assign the handling department (entry in 'DepartmentSignal')
-- If no rule matches, no action is required
- When a signal is split, the routing rules will be executed for the sub-signals
- We need to adjust the signals list end point to include the signal <-> department relation next to the existing category <-> department when retrieving signals for an user

### Front-end:
- Page to enter, test, submit expression and set relation with category/department (via expression and routing endpoint)
We could separate this into 2 steps: 
1. create, modify and test expression based on expression type using https://github.com/Signalen/backend/issues/61  (expression endpoint: this step can be re-used for email rules)
2. assign expressions rules to department (routing endpoint, via *RoutingRule* relation)

### Potential issues
- Do we expect 100, 500, 1k, 10k rules? If we have a lot of rules, we need to take this into account when executing rules.

### Backend
- Add model:
*SignalHandlingUser* (name to be determined, will hold the **optional** relation from signal to django user)
Fk to signal
Fk to django user record

- adjust private signal endpoint to allow for optional assignment of django user to signal (via *SignalHandlingUser* relation)
- add *SignalHandlingUser* data in list/get output

### Frontend
- in /manage/incidents overview, add column that can hold the optional django user name from *SignalHandlingUser*
- add action to allow assigning of django user to a signal
- add filter to enable filtering based on employee name via *SignalHandlingUser*

**Comment by erikveerm** [comment]
**Requirements Signal assignment**

- An employee can assign a signal to themselves; 
- Assigning a signal to another employee is only possible if you are authorized to do so; 
- A signal can be assigned to an employee who is a part of a department when this department is “responsible for the category” of the concering subcategory;

- If an employee changes departments and the new department isn’t “responsible for the category” he will no longer be able to adjust his previously assigned signals. 
1. Desired: The employee's name is automatically deleted; 
1. Manually adjust the employee's rights in SIA/Signals. 
1. Manually assign multiple signals to an employee at once (bulk action).

- Assignment List: 
1. Active Users SIA/Signals; 
1. Only employees of a department can be assigned to a signal which is assigned to that department; 
1. If the signal is assigned to a third party, then this party is a user in SIA/Signals and part of a department; 

- If a signal is being handled in another application (CityControl, HNW, Moon, etc.) it does not need to be assigned by name. It must be possible to send the signal assignment field in the API;    
- Autocomplete function by name when selecting an employee from a list;
- If a signal has been sent to an external organization (e.g. the police), the status of the signal is Forwarded (doorgestuurd). Desired: insight which signals have been forwarded to a specific organization; 

- Filters:
1. Filter by own signals (employee name)
1. Filter by name other employees of the same department
1. Filter by unassigned signals by department

- If someone is no longer a SIA/Signalen user (or has been made inactive) and has previous assigned signals, the name of must be automatically removed from the signal
-- To make an employee inactive is being done manually or through the  ADFS-interface.

- An employee can see a (newly) assigned signal by applying a filter on his name and sorting the list by date
-- Desired: send a push message to an employee when there are newly assigned signals.
1. Maybe in combination with the status Reported (gemeld). To avoid messages when you self assigned signals. 
2. Option: an e-mail with the general tekst: New signals with the status Reported have been assigned to your name.
3. Risk: you might miss newly assigned signals with a status other than Reported

- The requirements for reporting need to be shaped further.
