### ISSUE TITLE
Refactor Django Rest Framework (DRF)

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#7]
Original by @CBuiVNG 

Currently DRF has too many responsibilities. It includes auth, data serialization, partial business logic, data persistence. We should refactor this to separate layers.

- serialization with dataclass (using pydantic or similar. Validation should then be place at these objects)
- per object auth checks in the views. Move these out of DRF
- extract business logic (from DRF, FAT django models) to separate service layer (service layer)
- try to avoid using FAT models if possible

**Comment by spreeker** [comment]
Drf_amsterdam module was made by me. It would be trivial to create a drf_vngr one.

With like blue colors and a vng look.

**Comment by CBuiVNG** [comment]
On hold for now, will be postponed and implemented later
