### ISSUE TITLE
SIA in history/logging of a signal

### ISSUE THREAD

**Issue by erikveerm** [Signalen/backend#71]
**Describe the bug**
In the history of a signal, for example 211, the logging refers to "SIA systeem". Shouldn't this be _Signalen systeem_
![SIA systeem](https://user-images.githubusercontent.com/66015874/96727444-56b97300-13b3-11eb-923a-e6116d6af53f.PNG)

**Comment by boris-arkenaar** [comment]
@erikveerm This label resides in the backend.
Moved the issue to the backend repository.

**Comment by CBuiVNG** [comment]
Made a PR, and checking if there are objections for renaming this

**Comment by CBuiVNG** [comment]
I've double checked this issue with Amsterdam. They are going to ask if the new naming is ok. We could make it configurable if Amsterdam prefers to keep the current naming.
