### ISSUE TITLE
Research how we can make the automated categorization generic

### ISSUE THREAD

**Issue by bartjkdp** [Signalen/backend#8]
We would like to investigate how Den Bosch handles categories and how this relates to how Amsterdam does this.

- Get an overview of categories in Den Bosch
- Compare this with the categories in Amsterdam
- Get a dataset of signals from the past two years in Den Bosch
- Create an initial plan how we could create a general service

**Comment by jaccobrouwer** [comment]
https://www.mindsdb.com/ ... please check if this is something that could be beneficial(?)

**Comment by CBuiVNG** [comment]
Currently the ML endpoint only supports main and sub category. Is this sufficient for other municipalities? Or do we need to support an arbitrary tree of categories?

**Comment by CBuiVNG** [comment]
Initial findings:
- Duplicate text assigned to multiple categories. (sql join error?)

After removal of the duplicates:
- use stop words. Does increase prediction a bit
- use stemming. Not really noticeable 
- the messages seems to be prefix with "user_id:". This will cause issues when a single user enters multiple entries. Tested with a custom pre-processor that removes this user id. Improves prediction a bit
- some messages only have a number. There's probably a location stored somehwere (not exported). Makes it difficult to classify these.
